language: node_js
braches:
  only:
  - master
script: source publish
tmp: 
before_install:
- openssl aes-256-cbc -K $encrypted_b883d78a9832_key -iv $encrypted_b883d78a9832_iv
  -in publish-env.enc -out publish-env -d
- source publish-env
