language: node_js
braches:
  only:
  - master
script: source publish
tmp: 
before_install:
- openssl aes-256-cbc -K $encrypted_e14d7aa062e3_key -iv $encrypted_e14d7aa062e3_iv
  -in publish-env.enc -out publish-env -d
- source publish-env
