#!/bin/bash

# based on http://awestruct.org/auto-deploy-to-github-pages/

v=`git log --oneline | wc -l`
echo "Revision $v"
echo "{ \"revision\": $v }" > src/build/_data.json

./harp compile src dist
git checkout -- src/build/_data.json
ref=`git log | head -n 1`

[[ "${GIT_NAME}" != "" ]] && git config user.name "${GIT_NAME}"
[[ "${GIT_EMAIL}" != "" ]] && git config user.email "${GIT_EMAIL}"
if [ "${GH_TOKEN}" != "" ]; then
    git config credential.helper "store --file=.git/credentials"
    echo "https://${GH_TOKEN}:@github.com" > .git/credentials
fi

git remote set-url --push origin `git config remote.origin.url | sed 's/git:/https:/'`
git remote set-branches --add origin gh-pages
git fetch origin gh-pages
git checkout gh-pages

mkdir tmp
mv * tmp
mv tmp/dist/* .
rm -rf tmp

git add -A
git commit -am "publish ${ref}"
git push

git checkout master
