#!/bin/bash

# based on http://awestruct.org/auto-deploy-to-github-pages/

./harp compile src dist

git config user.name "${GIT_NAME}"
git config user.email "${GIT_EMAIL}"
git config credential.helper "store --file=.git/credentials"
echo "https://${GH_TOKEN}:@github.com" > .git/credentials

git remote set-url --push origin `git config remote.origin.url | sed 's/git:/https:/'`
git remote set-branches --add origin gh-pages
git fetch origin gh-pages
git checkout -b gh-pages origin/gh-pages

mkdir tmp
mv * tmp
mv tmp/dist/* .
rm -rf tmp

git add -A
git commit -am "deploy `git log | head -n 1`"
git push